package com.adobe.creativesdk.foundation.internal.collaboration;

/* JADX INFO: loaded from: classes.dex */
public enum AdobeCollaborationErrorCode {
    ADOBE_COLLABORATION_ERROR_UNEXPECTED_RESPONSE,
    ADOBE_COLLABORATION_ERROR_UNAUTHORIZED,
    ADOBE_COLLABORATION_ERROR_INVALID_FOLDER,
    ADOBE_COLLABORATION_ERROR_INVALID_EMAIL,
    ADOBE_COLLABORATION_ERROR_INVALID_USER_ID,
    ADOBE_COLLABORATION_ERROR_INVALID_INVITE_ID
}
