.class public interface abstract Lcom/behance/sdk/util/BehanceSDKFragmentTags;
.super Ljava/lang/Object;
.source "BehanceSDKFragmentTags.java"


# static fields
.field public static final FRAGMENT_TAG_ADD_PROJECT_ALBUM_SELECTION_FRAGMENT:Ljava/lang/String; = "FRAGMENT_TAG_ADD_PROJECT_ALBUM_SELECTION_FRAGMENT"

.field public static final FRAGMENT_TAG_ADD_PROJECT_COVER_NEW_IMAGE_SELECTION_FRAGMENT:Ljava/lang/String; = "FRAGMENT_TAG_ADD_PROJECT_COVER_NEW_IMAGE_SELECTION_FRAGMENT"

.field public static final FRAGMENT_TAG_ADD_PROJECT_COVER_SELECTION_FRAGMENT:Ljava/lang/String; = "FRAGMENT_TAG_ADD_PROJECT_COVER_SELECTION_FRAGMENT"

.field public static final FRAGMENT_TAG_ADD_PROJECT_EDIT_FRAGMENT:Ljava/lang/String; = "FRAGMENT_TAG_ADD_PROJECT_EDIT_FRAGMENT"

.field public static final FRAGMENT_TAG_ADD_PROJECT_IMAGE_SELECTION_FRAGMENT:Ljava/lang/String; = "FRAGMENT_TAG_ADD_PROJECT_IMAGE_SELECTION_FRAGMENT"

.field public static final FRAGMENT_TAG_ADD_PROJECT_PREVIEW_FRAGMENT:Ljava/lang/String; = "FRAGMENT_TAG_ADD_PROJECT_PREVIEW_FRAGMENT"

.field public static final FRAGMENT_TAG_ADD_PROJECT_PUBLISH_FRAGMENT:Ljava/lang/String; = "FRAGMENT_TAG_ADD_PROJECT_PUBLISH_FRAGMENT"

.field public static final FRAGMENT_TAG_COPYRIGHT_SETTINGS_DIALOG:Ljava/lang/String; = "FRAGMENT_TAG_COPYRIGHT_SETTINGS_DIALOG"

.field public static final FRAGMENT_TAG_CREATIVE_FIELDS_FILTER_DIALOG:Ljava/lang/String; = "FRAGMENT_TAG_CREATIVE_FIELDS_FILTER_DIALOG"

.field public static final FRAGMENT_TAG_ENTERPRISE_USER_WARNING_FRAGMENT:Ljava/lang/String; = "FRAGMENT_TAG_ENTERPRISE_USER_WARNING_FRAGMENT"
