package com.facebook.c.a;

/* JADX INFO: compiled from: CacheErrorLogger.java */
/* JADX INFO: loaded from: classes2.dex */
public enum b {
    READ_DECODE,
    READ_FILE,
    READ_FILE_NOT_FOUND,
    READ_INVALID_ENTRY,
    WRITE_ENCODE,
    WRITE_CREATE_TEMPFILE,
    WRITE_UPDATE_FILE_NOT_FOUND,
    WRITE_RENAME_FILE_TEMPFILE_NOT_FOUND,
    WRITE_RENAME_FILE_TEMPFILE_PARENT_NOT_FOUND,
    WRITE_RENAME_FILE_OTHER,
    WRITE_CREATE_DIR,
    WRITE_CALLBACK_ERROR,
    WRITE_INVALID_ENTRY,
    DELETE_FILE,
    EVICTION,
    GENERIC_IO,
    OTHER
}
